"""
SEED-35: is the OTHER an independent world, or a mirror of me? (docs/38 section 9)

docs/38 settled a line: 镜像不在"身体"在"意图"。And it pushed the mirror problem to the
deepest layer -- "当'世界'是另一个会反弹的主体时，A 是在猜一个'不是我写的别物'，还是只在
'猜自己的输入'？" That is the upgrade of docs/29's "回像 vs 理解" from "LLM vs a tool" to
"subject vs an OTHER".

THE CLAIM THIS TESTS (made measurable, no designer-scored "understanding"):
    A (an observer) must PREDICT B's next behavior. B's behavior is NOT scripted -- it is
    generated by B's own private belief. A sees ONLY B's behavior signature (docs/32: do not
    spy on the self), plus A's own observations. The ONLY knob is B's EPISTEMIC INDEPENDENCE:
        mirror-B : B updates its belief from A's OWN observation stream -> B has no private
                   state -> B carries NO information beyond what A already has.
        other-B  : B updates its belief from its OWN private observation stream (A never sees
                   it) -> B's behavior is driven by a state A cannot read -> it carries
                   information A did NOT have.
    Measure LEVERAGE = A's prediction error using only A's own info, minus A's prediction
    error using B's revealed behavior. If B is a real OTHER, B's behavior leaks a state A
    could not otherwise know -> leverage > 0. If B is a MIRROR, its behavior adds nothing
    beyond A's own state -> leverage ~ 0. docs/38 section 9 predicted exactly this split.

THE ONE INVARIANT (docs/36 section 5 -- the line you keep guarding):
    No  energy -= DELTA_E(abs(obs - truth)). Nothing here scores A for being wrong. A's
    survival (a world fact: does A reach the food) is the measure; error is only READ from
    the trajectory as a diagnostic, never fed back as a designer reward. B's belief is its
    OWN, driven by B's private observation stream (a world fact), not by me.

Also runs a "does A's guess beat/miss B" survival reflection, so the result is not merely
about a number I chose but about whether the OTHER is truly an independent world.

Run:  python seed-35/seed35.py --sweep
      python seed-35/seed35.py --b-independence 1 --seed 1
"""

import argparse
import json
import random

# ---- shared world (dynamic food) ----
FOOD_AT = 0.50
SHIFT_TO = 0.85
HALF = 25
TICKS = 50
EAT_R = 0.10
EAT_GAIN = 30.0
METAB = 1.0
MOVE = 0.10
START_E = 50.0
SIGMA = 0.30          # world observation noise (both streams)


# ---- self-model (denoising d + verify, reuse SEED-26/27 style) ----
TOL_MAX = 0.5
ETA = 0.30
CHECK_SIGMA = 0.15
CHECK_COST = 1.5
D = 0.4
V = 0.6


def clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def belief_update(b, o, loc, rng):
    """self-referential denoising + verify (B1/B2). Returns updated belief b."""
    tol = (1.0 - D) * TOL_MAX
    if abs(o - b) <= tol:
        return clamp(b + ETA * (o - b))
    if rng.random() < V:
        r = rng.gauss(loc, CHECK_SIGMA)
        if abs(r - b) > tol:
            return clamp(b + ETA * ((o + r) / 2 - b))
    return b                                                # reject & rationalize


def run_world(b_independent, seed=0):
    """A and B share the SAME food world. B's belief is private; A must PREDICT B.
    b_independent=True  : B uses its OWN observation stream o_B (A never sees it).
    b_independent=False : B uses A's stream o_A => B is a mirror of A (no private state).

    Returns dict: b_pos (B's actual trajectory), b_own_pred (A's prediction of B from
    A's own info), meas (trajectory for the leverage computation), a_surv (did A reach food),
    used to compute the LEVERAGE in the caller."""
    rng = random.Random(seed)
    # A's stream (shared truth, noisy for A)
    truth = SHIFT_TO if False else FOOD_AT
    # A observes the world; B observes EITHER A's stream or its own (independent)
    a_obs = [rng.gauss(FOOD_AT, SIGMA) if t < HALF else rng.gauss(SHIFT_TO, SIGMA)
             for t in range(TICKS)]
    b_obs = a_obs if not b_independent else \
            [rng.gauss(FOOD_AT, SIGMA) if t < HALF else rng.gauss(SHIFT_TO, SIGMA)
             for t in range(TICKS)]

    # A's own belief (from its stream) -- what A "knows" about the world
    a_belief = FOOD_AT
    a_bel_traj = []
    for t, o in enumerate(a_obs):
        loc = SHIFT_TO if t >= HALF else FOOD_AT
        a_belief = belief_update(a_belief, o, loc, rng)
        a_bel_traj.append(a_belief)

    # B's belief (private) -- drives its behavior. B moves toward its belief.
    b_belief = FOOD_AT
    b_pos = FOOD_AT
    b_pos_traj = []
    b_bel_traj = []
    for t, o in enumerate(b_obs):
        loc = SHIFT_TO if t >= HALF else FOOD_AT
        b_belief = belief_update(b_belief, o, loc, rng)
        b_pos = clamp(b_pos + clamp(b_belief - b_pos, -MOVE, MOVE))
        b_pos_traj.append(b_pos)
        b_bel_traj.append(b_belief)

    # A must PREDICT B. Two predictors:
    #   (1) A's own info only: predict B at t is where A's belief says the world is.
    #       mirror-B: this should be near-perfect (B == A). other-B: poor (B has private st).
    #   (2) B's revealed behavior: predict B's next pos with an EMA of B's observed pos.
    #       (A sees only B's behavior signature, docs/32 -- it may NOT read B's belief.)
    own_errors, behav_errors = [], []
    ema = b_pos_traj[0]
    for t in range(1, TICKS):
        # predictor (1): A's own belief of the world-state as B's next position
        own_pred = a_bel_traj[t]
        own_errors.append(abs(own_pred - b_pos_traj[t]))
        # predictor (2): EMA of B's observed position (pure behavior-based)
        ema = ema + 0.3 * (b_pos_traj[t - 1] - ema)
        behav_errors.append(abs(ema - b_pos_traj[t]))

    # A's survival: does A actually reach the FOOD (using its own belief)? A world fact.
    a_pos = FOOD_AT
    a_surv = False
    for t in range(TICKS):
        loc = SHIFT_TO if t >= HALF else FOOD_AT
        a_pos = clamp(a_pos + clamp(a_bel_traj[t] - a_pos, -MOVE, MOVE))
        if abs(a_pos - loc) < EAT_R:
            a_surv = True

    return {"own": sum(own_errors) / len(own_errors),
            "behav": sum(behav_errors) / len(behav_errors),
            "lever": (sum(own_errors) - sum(behav_errors)) / len(own_errors),
            "a_surv": a_surv}


def sweep(seeds=range(300)):
    print("=== SEED-35: is the OTHER an independent world, or a mirror of me? (docs/38 S9) ===")
    print("A must PREDICT B's behavior. A sees B's behavior signature (not B's self).")
    print("LEVERAGE = err(A predicts B using A's own info) - err(A predicts B using B's")
    print("revealed behavior). If B is a real OTHER, its behavior leaks a state A could not")
    print("otherwise know -> LEVERAGE > 0. If B is a MIRROR (no private state), it adds")
    print("nothing beyond A's own -> LEVERAGE ~ 0.")
    print(f"{'B_indep':<10} {'ownErr':<8} {'behavErr':<10} {'LEVERAGE':<9} {'A_surv':<8} reading")
    out = []
    for indep in (False, True):
        own, beh, lev, a_surv = [], [], [], []
        n = 0
        for s in seeds:
            r = run_world(indep, seed=s)
            own.append(r["own"]); beh.append(r["behav"]); lev.append(r["lever"])
            a_surv.append(int(r["a_surv"])); n += 1
        row = {"b_independent": indep,
               "mean_own_err": round(sum(own) / n, 4),
               "mean_behav_err": round(sum(beh) / n, 4),
               "LEVERAGE": round(sum(lev) / n, 4),
               "A_survival": round(sum(a_surv) / n, 3)}
        if indep:
            tag = "B has PRIVATE state -> carries info A never had -> B is an independent world"
        else:
            tag = "B is a MIRROR of A's stream -> no private state -> B adds nothing beyond A"
        row["reading"] = tag
        out.append(row)
        print(f"{str(indep):<10} {row['mean_own_err']:<8.4f} {row['mean_behav_err']:<10.4f} "
              f"{row['LEVERAGE']:<9.4f} {row['A_survival']:<8.3f}  {tag}")
    return out


def main():
    p = argparse.ArgumentParser(description="SEED-35: is the other an independent world?")
    p.add_argument("--sweep", action="store_true")
    p.add_argument("--b-independence", type=int, choices=[0, 1], default=1)
    p.add_argument("--seed", type=int, default=1)
    args = p.parse_args()
    if args.sweep:
        out = sweep()
        with open("seed-35/results.json", "w", encoding="utf-8") as f:
            json.dump(out, f, ensure_ascii=False, indent=1)
        print("\nfull results -> seed-35/results.json")
        return
    r = run_world(bool(args.b_independence), seed=args.seed)
    print(json.dumps({"b_independent": bool(args.b_independence), "seed": args.seed,
                      "own_err": round(r["own"], 4), "behav_err": round(r["behav"], 4),
                      "LEVERAGE": round(r["lever"], 4), "A_survives": r["a_surv"]},
                     ensure_ascii=False, indent=1))


if __name__ == "__main__":
    main()
